// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppProfiles(arg1) {
  return window['go']['starrs']['Starrs']['AppProfiles'](arg1);
}

export function BlockList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['starrs']['Starrs']['BlockList'](arg1, arg2, arg3, arg4, arg5);
}

export function CustomFilters(arg1) {
  return window['go']['starrs']['Starrs']['CustomFilters'](arg1);
}

export function DeleteBlockList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteBlockList'](arg1, arg2);
}

export function DeleteDownloader(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteDownloader'](arg1, arg2);
}

export function DeleteExclusion(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteExclusion'](arg1, arg2);
}

export function DeleteImportList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteImportList'](arg1, arg2);
}

export function DeleteIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteIndexer'](arg1, arg2);
}

export function DeleteQualityProfile(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteQualityProfile'](arg1, arg2);
}

export function DeleteRootFolder(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteRootFolder'](arg1, arg2);
}

export function Downloaders(arg1) {
  return window['go']['starrs']['Starrs']['Downloaders'](arg1);
}

export function Exclusions(arg1) {
  return window['go']['starrs']['Starrs']['Exclusions'](arg1);
}

export function ExportLidarrDownloadClients(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportLidarrDownloadClients'](arg1, arg2);
}

export function ExportLidarrExclusions(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportLidarrExclusions'](arg1, arg2);
}

export function ExportLidarrImportLists(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportLidarrImportLists'](arg1, arg2);
}

export function ExportLidarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportLidarrIndexer'](arg1, arg2);
}

export function ExportProwlarrDownloadClients(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportProwlarrDownloadClients'](arg1, arg2);
}

export function ExportProwlarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportProwlarrIndexer'](arg1, arg2);
}

export function ExportRadarrDownloadClients(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportRadarrDownloadClients'](arg1, arg2);
}

export function ExportRadarrExclusions(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportRadarrExclusions'](arg1, arg2);
}

export function ExportRadarrImportLists(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportRadarrImportLists'](arg1, arg2);
}

export function ExportRadarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportRadarrIndexer'](arg1, arg2);
}

export function ExportReadarrDownloadClients(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportReadarrDownloadClients'](arg1, arg2);
}

export function ExportReadarrExclusions(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportReadarrExclusions'](arg1, arg2);
}

export function ExportReadarrImportLists(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportReadarrImportLists'](arg1, arg2);
}

export function ExportReadarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportReadarrIndexer'](arg1, arg2);
}

export function ExportSonarrDownloadClients(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportSonarrDownloadClients'](arg1, arg2);
}

export function ExportSonarrExclusions(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportSonarrExclusions'](arg1, arg2);
}

export function ExportSonarrImportLists(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportSonarrImportLists'](arg1, arg2);
}

export function ExportSonarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportSonarrIndexer'](arg1, arg2);
}

export function ExportWhisparrDownloadClients(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportWhisparrDownloadClients'](arg1, arg2);
}

export function ExportWhisparrExclusions(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportWhisparrExclusions'](arg1, arg2);
}

export function ExportWhisparrImportLists(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportWhisparrImportLists'](arg1, arg2);
}

export function ExportWhisparrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['ExportWhisparrIndexer'](arg1, arg2);
}

export function ImportLidarrDownloadClients(arg1) {
  return window['go']['starrs']['Starrs']['ImportLidarrDownloadClients'](arg1);
}

export function ImportLidarrExclusions(arg1) {
  return window['go']['starrs']['Starrs']['ImportLidarrExclusions'](arg1);
}

export function ImportLidarrImportLists(arg1) {
  return window['go']['starrs']['Starrs']['ImportLidarrImportLists'](arg1);
}

export function ImportLidarrIndexer(arg1) {
  return window['go']['starrs']['Starrs']['ImportLidarrIndexer'](arg1);
}

export function ImportLists(arg1) {
  return window['go']['starrs']['Starrs']['ImportLists'](arg1);
}

export function ImportProwlarrDownloadClients(arg1) {
  return window['go']['starrs']['Starrs']['ImportProwlarrDownloadClients'](arg1);
}

export function ImportProwlarrIndexer(arg1) {
  return window['go']['starrs']['Starrs']['ImportProwlarrIndexer'](arg1);
}

export function ImportRadarrDownloadClients(arg1) {
  return window['go']['starrs']['Starrs']['ImportRadarrDownloadClients'](arg1);
}

export function ImportRadarrExclusions(arg1) {
  return window['go']['starrs']['Starrs']['ImportRadarrExclusions'](arg1);
}

export function ImportRadarrImportLists(arg1) {
  return window['go']['starrs']['Starrs']['ImportRadarrImportLists'](arg1);
}

export function ImportRadarrIndexer(arg1) {
  return window['go']['starrs']['Starrs']['ImportRadarrIndexer'](arg1);
}

export function ImportReadarrDownloadClients(arg1) {
  return window['go']['starrs']['Starrs']['ImportReadarrDownloadClients'](arg1);
}

export function ImportReadarrExclusions(arg1) {
  return window['go']['starrs']['Starrs']['ImportReadarrExclusions'](arg1);
}

export function ImportReadarrImportLists(arg1) {
  return window['go']['starrs']['Starrs']['ImportReadarrImportLists'](arg1);
}

export function ImportReadarrIndexer(arg1) {
  return window['go']['starrs']['Starrs']['ImportReadarrIndexer'](arg1);
}

export function ImportSonarrDownloadClients(arg1) {
  return window['go']['starrs']['Starrs']['ImportSonarrDownloadClients'](arg1);
}

export function ImportSonarrExclusions(arg1) {
  return window['go']['starrs']['Starrs']['ImportSonarrExclusions'](arg1);
}

export function ImportSonarrImportLists(arg1) {
  return window['go']['starrs']['Starrs']['ImportSonarrImportLists'](arg1);
}

export function ImportSonarrIndexer(arg1) {
  return window['go']['starrs']['Starrs']['ImportSonarrIndexer'](arg1);
}

export function ImportWhisparrDownloadClients(arg1) {
  return window['go']['starrs']['Starrs']['ImportWhisparrDownloadClients'](arg1);
}

export function ImportWhisparrExclusions(arg1) {
  return window['go']['starrs']['Starrs']['ImportWhisparrExclusions'](arg1);
}

export function ImportWhisparrImportLists(arg1) {
  return window['go']['starrs']['Starrs']['ImportWhisparrImportLists'](arg1);
}

export function ImportWhisparrIndexer(arg1) {
  return window['go']['starrs']['Starrs']['ImportWhisparrIndexer'](arg1);
}

export function Indexers(arg1) {
  return window['go']['starrs']['Starrs']['Indexers'](arg1);
}

export function MetadataProfiles(arg1) {
  return window['go']['starrs']['Starrs']['MetadataProfiles'](arg1);
}

export function MigratorInfo(arg1) {
  return window['go']['starrs']['Starrs']['MigratorInfo'](arg1);
}

export function QualityProfiles(arg1) {
  return window['go']['starrs']['Starrs']['QualityProfiles'](arg1);
}

export function RootFolders(arg1) {
  return window['go']['starrs']['Starrs']['RootFolders'](arg1);
}

export function Tags(arg1) {
  return window['go']['starrs']['Starrs']['Tags'](arg1);
}

export function TestInstance(arg1) {
  return window['go']['starrs']['Starrs']['TestInstance'](arg1);
}

export function TestLidarrDownloadClient(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestLidarrDownloadClient'](arg1, arg2);
}

export function TestLidarrImportList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestLidarrImportList'](arg1, arg2);
}

export function TestLidarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestLidarrIndexer'](arg1, arg2);
}

export function TestProwlarrDownloadClient(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestProwlarrDownloadClient'](arg1, arg2);
}

export function TestProwlarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestProwlarrIndexer'](arg1, arg2);
}

export function TestRadarrDownloadClient(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestRadarrDownloadClient'](arg1, arg2);
}

export function TestRadarrImportList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestRadarrImportList'](arg1, arg2);
}

export function TestRadarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestRadarrIndexer'](arg1, arg2);
}

export function TestReadarrDownloadClient(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestReadarrDownloadClient'](arg1, arg2);
}

export function TestReadarrImportList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestReadarrImportList'](arg1, arg2);
}

export function TestReadarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestReadarrIndexer'](arg1, arg2);
}

export function TestSonarrDownloadClient(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestSonarrDownloadClient'](arg1, arg2);
}

export function TestSonarrImportList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestSonarrImportList'](arg1, arg2);
}

export function TestSonarrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestSonarrIndexer'](arg1, arg2);
}

export function TestWhisparrDownloadClient(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestWhisparrDownloadClient'](arg1, arg2);
}

export function TestWhisparrImportList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestWhisparrImportList'](arg1, arg2);
}

export function TestWhisparrIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['TestWhisparrIndexer'](arg1, arg2);
}

export function UpdateInvalidItems(arg1, arg2, arg3, arg4) {
  return window['go']['starrs']['Starrs']['UpdateInvalidItems'](arg1, arg2, arg3, arg4);
}

export function UpdateLidarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateLidarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateLidarrExclusion(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateLidarrExclusion'](arg1, arg2);
}

export function UpdateLidarrImportList(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateLidarrImportList'](arg1, arg2, arg3);
}

export function UpdateLidarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateLidarrIndexer'](arg1, arg2, arg3);
}

export function UpdateLidarrQualityProfile(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateLidarrQualityProfile'](arg1, arg2);
}

export function UpdateProwlarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateProwlarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateProwlarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateProwlarrIndexer'](arg1, arg2, arg3);
}

export function UpdateRadarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateRadarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateRadarrExclusion(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateRadarrExclusion'](arg1, arg2);
}

export function UpdateRadarrImportList(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateRadarrImportList'](arg1, arg2, arg3);
}

export function UpdateRadarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateRadarrIndexer'](arg1, arg2, arg3);
}

export function UpdateRadarrQualityProfile(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateRadarrQualityProfile'](arg1, arg2);
}

export function UpdateReadarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateReadarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateReadarrExclusion(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateReadarrExclusion'](arg1, arg2);
}

export function UpdateReadarrImportList(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateReadarrImportList'](arg1, arg2, arg3);
}

export function UpdateReadarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateReadarrIndexer'](arg1, arg2, arg3);
}

export function UpdateReadarrQualityProfile(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateReadarrQualityProfile'](arg1, arg2);
}

export function UpdateRecycleBin(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateRecycleBin'](arg1, arg2);
}

export function UpdateRootFolder(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateRootFolder'](arg1, arg2, arg3);
}

export function UpdateSonarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateSonarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateSonarrExclusion(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateSonarrExclusion'](arg1, arg2);
}

export function UpdateSonarrImportList(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateSonarrImportList'](arg1, arg2, arg3);
}

export function UpdateSonarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateSonarrIndexer'](arg1, arg2, arg3);
}

export function UpdateSonarrQualityProfile(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateSonarrQualityProfile'](arg1, arg2);
}

export function UpdateWhisparrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateWhisparrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateWhisparrExclusion(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateWhisparrExclusion'](arg1, arg2);
}

export function UpdateWhisparrImportList(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateWhisparrImportList'](arg1, arg2, arg3);
}

export function UpdateWhisparrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateWhisparrIndexer'](arg1, arg2, arg3);
}

export function UpdateWhisparrQualityProfile(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateWhisparrQualityProfile'](arg1, arg2);
}
