// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppProfiles(arg1:any):Promise<any>;

export function BlockList(arg1:any):Promise<any>;

export function CustomFilters(arg1:any):Promise<any>;

export function DeleteBlockLists(arg1:any,arg2:Array<number>):Promise<any>;

export function DeleteRootFolder(arg1:any,arg2:string):Promise<any>;

export function Downloaders(arg1:any):Promise<any>;

export function Exclusions(arg1:any):Promise<any>;

export function ImportLists(arg1:any):Promise<any>;

export function Indexers(arg1:any):Promise<any>;

export function MigratorInfo(arg1:any):Promise<any>;

export function QualityProfiles(arg1:any):Promise<any>;

export function TestInstance(arg1:any):Promise<string>;

export function UpdateInvalidItems(arg1:any,arg2:string,arg3:string,arg4:{[key: number]: boolean}):Promise<any>;

export function UpdateRecycleBin(arg1:any,arg2:string):Promise<any>;

export function UpdateRootFolder(arg1:any,arg2:string,arg3:string):Promise<any>;
