// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppProfiles(arg1:any):Promise<any>;

export function BlockList(arg1:any,arg2:number,arg3:number,arg4:string,arg5:string):Promise<any>;

export function CustomFilters(arg1:any):Promise<any>;

export function DeleteBlockList(arg1:any,arg2:number):Promise<any>;

export function DeleteDownloader(arg1:any,arg2:number):Promise<any>;

export function DeleteExclusion(arg1:any,arg2:number):Promise<any>;

export function DeleteImportList(arg1:any,arg2:number):Promise<any>;

export function DeleteIndexer(arg1:any,arg2:number):Promise<any>;

export function DeleteQualityProfile(arg1:any,arg2:number):Promise<any>;

export function DeleteRootFolder(arg1:any,arg2:string):Promise<any>;

export function Downloaders(arg1:any):Promise<any>;

export function Exclusions(arg1:any):Promise<any>;

export function ImportLists(arg1:any):Promise<any>;

export function Indexers(arg1:any):Promise<any>;

export function MetadataProfiles(arg1:any):Promise<any>;

export function MigratorInfo(arg1:any):Promise<any>;

export function QualityProfiles(arg1:any):Promise<any>;

export function RootFolders(arg1:any):Promise<any>;

export function Tags(arg1:any):Promise<{[key: number]: string}>;

export function TestInstance(arg1:any):Promise<string>;

export function UpdateInvalidItems(arg1:any,arg2:string,arg3:string,arg4:{[key: number]: boolean}):Promise<any>;

export function UpdateLidarrDownloadClient(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateLidarrExclusion(arg1:any,arg2:any):Promise<any>;

export function UpdateLidarrImportList(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateLidarrIndexer(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateLidarrQualityProfile(arg1:any,arg2:any):Promise<any>;

export function UpdateProwlarrDownloadClient(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateProwlarrIndexer(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateRadarrDownloadClient(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateRadarrExclusion(arg1:any,arg2:any):Promise<any>;

export function UpdateRadarrImportList(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateRadarrIndexer(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateRadarrQualityProfile(arg1:any,arg2:any):Promise<any>;

export function UpdateReadarrDownloadClient(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateReadarrExclusion(arg1:any,arg2:any):Promise<any>;

export function UpdateReadarrImportList(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateReadarrIndexer(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateReadarrQualityProfile(arg1:any,arg2:any):Promise<any>;

export function UpdateRecycleBin(arg1:any,arg2:string):Promise<any>;

export function UpdateRootFolder(arg1:any,arg2:string,arg3:string):Promise<any>;

export function UpdateSonarrDownloadClient(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateSonarrExclusion(arg1:any,arg2:any):Promise<any>;

export function UpdateSonarrImportList(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateSonarrIndexer(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateSonarrQualityProfile(arg1:any,arg2:any):Promise<any>;

export function UpdateWhisparrDownloadClient(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateWhisparrExclusion(arg1:any,arg2:any):Promise<any>;

export function UpdateWhisparrImportList(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateWhisparrIndexer(arg1:any,arg2:boolean,arg3:any):Promise<any>;

export function UpdateWhisparrQualityProfile(arg1:any,arg2:any):Promise<any>;
