// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRootFolder(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteRootFolder'](arg1, arg2);
}

export function MigratorInfo(arg1) {
  return window['go']['starrs']['Starrs']['MigratorInfo'](arg1);
}

export function TestInstance(arg1) {
  return window['go']['starrs']['Starrs']['TestInstance'](arg1);
}

export function UpdateInvalidItems(arg1, arg2, arg3, arg4) {
  return window['go']['starrs']['Starrs']['UpdateInvalidItems'](arg1, arg2, arg3, arg4);
}

export function UpdateRecycleBin(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateRecycleBin'](arg1, arg2);
}

export function UpdateRootFolder(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateRootFolder'](arg1, arg2, arg3);
}
