// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppProfiles(arg1) {
  return window['go']['starrs']['Starrs']['AppProfiles'](arg1);
}

export function BlockList(arg1) {
  return window['go']['starrs']['Starrs']['BlockList'](arg1);
}

export function CustomFilters(arg1) {
  return window['go']['starrs']['Starrs']['CustomFilters'](arg1);
}

export function DeleteBlockList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteBlockList'](arg1, arg2);
}

export function DeleteDownloader(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteDownloader'](arg1, arg2);
}

export function DeleteExclusions(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteExclusions'](arg1, arg2);
}

export function DeleteImportList(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteImportList'](arg1, arg2);
}

export function DeleteIndexer(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteIndexer'](arg1, arg2);
}

export function DeleteQualityProfile(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteQualityProfile'](arg1, arg2);
}

export function DeleteRootFolder(arg1, arg2) {
  return window['go']['starrs']['Starrs']['DeleteRootFolder'](arg1, arg2);
}

export function Downloaders(arg1) {
  return window['go']['starrs']['Starrs']['Downloaders'](arg1);
}

export function Exclusions(arg1) {
  return window['go']['starrs']['Starrs']['Exclusions'](arg1);
}

export function ImportLists(arg1) {
  return window['go']['starrs']['Starrs']['ImportLists'](arg1);
}

export function Indexers(arg1) {
  return window['go']['starrs']['Starrs']['Indexers'](arg1);
}

export function MigratorInfo(arg1) {
  return window['go']['starrs']['Starrs']['MigratorInfo'](arg1);
}

export function QualityProfiles(arg1) {
  return window['go']['starrs']['Starrs']['QualityProfiles'](arg1);
}

export function Tags(arg1) {
  return window['go']['starrs']['Starrs']['Tags'](arg1);
}

export function TestInstance(arg1) {
  return window['go']['starrs']['Starrs']['TestInstance'](arg1);
}

export function UpdateInvalidItems(arg1, arg2, arg3, arg4) {
  return window['go']['starrs']['Starrs']['UpdateInvalidItems'](arg1, arg2, arg3, arg4);
}

export function UpdateLidarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateLidarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateLidarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateLidarrIndexer'](arg1, arg2, arg3);
}

export function UpdateProwlarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateProwlarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateProwlarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateProwlarrIndexer'](arg1, arg2, arg3);
}

export function UpdateRadarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateRadarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateRadarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateRadarrIndexer'](arg1, arg2, arg3);
}

export function UpdateReadarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateReadarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateReadarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateReadarrIndexer'](arg1, arg2, arg3);
}

export function UpdateRecycleBin(arg1, arg2) {
  return window['go']['starrs']['Starrs']['UpdateRecycleBin'](arg1, arg2);
}

export function UpdateRootFolder(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateRootFolder'](arg1, arg2, arg3);
}

export function UpdateSonarrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateSonarrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateSonarrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateSonarrIndexer'](arg1, arg2, arg3);
}

export function UpdateWhisparrDownloadClient(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateWhisparrDownloadClient'](arg1, arg2, arg3);
}

export function UpdateWhisparrIndexer(arg1, arg2, arg3) {
  return window['go']['starrs']['Starrs']['UpdateWhisparrIndexer'](arg1, arg2, arg3);
}
