// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"fr_CH": &dictionary{index: fr_CHIndex, data: fr_CHData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"...continuing: ":                                    28,
	"Checked Current %s release: %v (%s)":                11,
	"Checking for current %s release: %v":                9,
	"Choose Folder":                                      6,
	"Closing Logger":                                     30,
	"Config %s":                                          5,
	"Config Problem":                                     8,
	"Downloading %s release from %s to %s (%s)":          16,
	"Downloading %s to %s":                               17,
	"Downloading %s update: %v":                          14,
	"Downloading File":                                   12,
	"Error writing config: %v":                           2,
	"Go Panic! This is a bug!\n%s-%s %s %v\n%s":          29,
	"Launching Installer: %s":                            19,
	"Launching installer: %s: %v":                        18,
	"Opening Folder: %s: %v":                             20,
	"Opening Path: %s":                                   21,
	"Saved: '%s' Value: %v":                              4,
	"Writing config: decoding '%s' value '%v' error: %v": 0,
	"[DEBUG] %s":                                         25,
	"[ERROR] %s":                                         22,
	"[FATAL] %s":                                         27,
	"[INFO] %s":                                          24,
	"[TRACE] %s":                                         26,
	"[WARN] %s":                                          23,
	"checking for current %s release:":                   10,
	"closing log rotator:":                               31,
	"decoding '%s' value '%v' error:":                    1,
	"downloading failed:":                                15,
	"missing release, check first?":                      13,
	"opening directory browser:":                         7,
	"writing config:":                                    3,
}

var de_DEIndex = []uint32{ // 33 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000,
} // Size: 156 bytes

const de_DEData string = ""

var en_USIndex = []uint32{ // 33 elements
	// Entry 0 - 1F
	0x00000000, 0x0000003c, 0x00000062, 0x0000007e,
	0x0000008e, 0x000000aa, 0x000000b7, 0x000000c5,
	0x000000e0, 0x000000ef, 0x00000119, 0x0000013d,
	0x0000016a, 0x0000017b, 0x00000199, 0x000001b9,
	0x000001cd, 0x00000203, 0x0000021e, 0x00000240,
	0x0000025b, 0x00000278, 0x0000028c, 0x0000029a,
	0x000002a7, 0x000002b4, 0x000002c2, 0x000002d0,
	0x000002de, 0x000002f2, 0x00000329, 0x00000338,
	// Entry 20 - 3F
	0x0000034d,
} // Size: 156 bytes

const en_USData string = "" + // Size: 845 bytes
	"\x02Writing config: decoding '%[1]s' value '%[2]v' error: %[3]v\x02decod" +
	"ing '%[1]s' value '%[2]v' error:\x02Error writing config: %[1]v\x02writi" +
	"ng config:\x02Saved: '%[1]s' Value: %[2]v\x02Config %[1]s\x02Choose Fold" +
	"er\x02opening directory browser:\x02Config Problem\x02Checking for curre" +
	"nt %[1]s release: %[2]v\x02checking for current %[1]s release:\x02Checke" +
	"d Current %[1]s release: %[2]v (%[3]s)\x02Downloading File\x02missing re" +
	"lease, check first?\x02Downloading %[1]s update: %[2]v\x02downloading fa" +
	"iled:\x02Downloading %[1]s release from %[2]s to %[3]s (%[4]s)\x02Downlo" +
	"ading %[1]s to %[2]s\x02Launching installer: %[1]s: %[2]v\x02Launching I" +
	"nstaller: %[1]s\x02Opening Folder: %[1]s: %[2]v\x02Opening Path: %[1]s" +
	"\x02[ERROR] %[1]s\x02[WARN] %[1]s\x02[INFO] %[1]s\x02[DEBUG] %[1]s\x02[T" +
	"RACE] %[1]s\x02[FATAL] %[1]s\x04\x00\x01 \x0f\x02...continuing:\x02Go Pa" +
	"nic! This is a bug!\x0a%[1]s-%[2]s %[3]s %[4]v\x0a%[5]s\x02Closing Logge" +
	"r\x02closing log rotator:"

var fr_CHIndex = []uint32{ // 33 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000,
} // Size: 156 bytes

const fr_CHData string = ""

// Total table size 1313 bytes (1KiB); checksum: C61DC773
