import {
  DeleteBlockList,
  DeleteDownloader,
  DeleteExclusion,
  DeleteIndexer,
  DeleteQualityProfile,
  DeleteImportList,
  UpdateLidarrDownloadClient,
  UpdateLidarrImportList,
  UpdateLidarrIndexer,
  UpdateLidarrQualityProfile,
  UpdateProwlarrDownloadClient,
  UpdateProwlarrIndexer,
  UpdateRadarrDownloadClient,
  UpdateRadarrImportList,
  UpdateRadarrIndexer,
  UpdateRadarrQualityProfile,
  UpdateReadarrDownloadClient,
  UpdateReadarrImportList,
  UpdateReadarrIndexer,
  UpdateReadarrQualityProfile,
  UpdateSonarrDownloadClient,
  UpdateSonarrImportList,
  UpdateSonarrIndexer,
  UpdateSonarrQualityProfile,
  UpdateWhisparrDownloadClient,
  UpdateWhisparrImportList,
  UpdateWhisparrIndexer,
  UpdateWhisparrQualityProfile,
  UpdateLidarrExclusion,
  UpdateRadarrExclusion,
  UpdateReadarrExclusion,
  UpdateSonarrExclusion,
  UpdateWhisparrExclusion,
  TestLidarrIndexer,
  TestProwlarrIndexer,
  TestReadarrIndexer,
  TestRadarrIndexer,
  TestSonarrIndexer,
  TestWhisparrIndexer,
  TestLidarrDownloadClient,
  TestProwlarrDownloadClient,
  TestReadarrDownloadClient,
  TestRadarrDownloadClient,
  TestSonarrDownloadClient,
  TestWhisparrDownloadClient,
  TestLidarrImportList,
  TestRadarrImportList,
  TestReadarrImportList,
  TestSonarrImportList,
  TestWhisparrImportList,
  ExportDownloadClients,
  ExportIndexer,
  ExportImportLists,
  ExportExclusions,
  ImportDownloadClients,
  ImportIndexer,
  ImportImportLists,
  ImportExclusions,
  AddLidarrDownloadClient,
  AddProwlarrDownloadClient,
  AddRadarrDownloadClient,
  AddReadarrDownloadClient,
  AddSonarrDownloadClient,
  AddWhisparrDownloadClient,
  AddLidarrIndexer,
  AddProwlarrIndexer,
  AddRadarrIndexer,
  AddReadarrIndexer,
  AddSonarrIndexer,
  AddWhisparrIndexer,
  AddLidarrImportList,
  AddRadarrImportList,
  AddReadarrImportList,
  AddSonarrImportList,
  AddWhisparrImportList,
  AddLidarrExclusion,
  AddRadarrExclusion,
  AddReadarrExclusion,
  AddSonarrExclusion,
  AddWhisparrExclusion,
  AddLidarrQualityProfile,
  AddRadarrQualityProfile,
  AddReadarrQualityProfile,
  AddSonarrQualityProfile,
  AddWhisparrQualityProfile,
  ImportQualityProfiles,
  ExportQualityProfiles,
} from "/wailsjs/go/starrs/Starrs"

export function fixFieldValues(info: {[key: string]: any}): string {
  info.forEach((item, idx) => {
    if (!item.fields) return
    item.fields.forEach((field, itemIdx) => {
      if (field.value === undefined || field.value === null) info[idx].fields[itemIdx].value = ""
    })
  })

  return JSON.stringify(info)
}

export const remove: {[key: string]: {[key: string]: (...args: any[]) => Promise<any>;}} = {
  "BlockLists": {
    "Lidarr":   DeleteBlockList,
    "Prowlarr": DeleteBlockList,
    "Radarr":   DeleteBlockList,
    "Readarr":  DeleteBlockList,
    "Sonarr":   DeleteBlockList,
    "Whisparr": DeleteBlockList,
  },
  "DownloadClients": {
    "Lidarr":   DeleteDownloader,
    "Prowlarr": DeleteDownloader,
    "Radarr":   DeleteDownloader,
    "Readarr":  DeleteDownloader,
    "Sonarr":   DeleteDownloader,
    "Whisparr": DeleteDownloader,
  },
  "Indexers": {
    "Lidarr":   DeleteIndexer,
    "Prowlarr": DeleteIndexer,
    "Radarr":   DeleteIndexer,
    "Readarr":  DeleteIndexer,
    "Sonarr":   DeleteIndexer,
    "Whisparr": DeleteIndexer,
  },
  "QualityProfiles": {
    "Lidarr":   DeleteQualityProfile,
    "Prowlarr": DeleteQualityProfile,
    "Radarr":   DeleteQualityProfile,
    "Readarr":  DeleteQualityProfile,
    "Sonarr":   DeleteQualityProfile,
    "Whisparr": DeleteQualityProfile,
  },
  "ImportLists": {
    "Lidarr":   DeleteImportList,
    "Prowlarr": DeleteImportList,
    "Radarr":   DeleteImportList,
    "Readarr":  DeleteImportList,
    "Sonarr":   DeleteImportList,
    "Whisparr": DeleteImportList,
  },
  "Exclusions": {
    "Lidarr": DeleteExclusion,
    "Radarr": DeleteExclusion,
    "Readarr": DeleteExclusion,
    "Sonarr": DeleteExclusion,
    "Whisparr": DeleteExclusion,
  }
}

export const update: {[key: string]: {[key: string]: (...args: any[]) => Promise<any>;}} = {
  "DownloadClients": {
    "Lidarr":   UpdateLidarrDownloadClient,
    "Prowlarr": UpdateProwlarrDownloadClient,
    "Radarr":   UpdateRadarrDownloadClient,
    "Readarr":  UpdateReadarrDownloadClient,
    "Sonarr":   UpdateSonarrDownloadClient,
    "Whisparr": UpdateWhisparrDownloadClient,
  },
  "Indexers": {
    "Lidarr":   UpdateLidarrIndexer,
    "Prowlarr": UpdateProwlarrIndexer,
    "Radarr":   UpdateRadarrIndexer,
    "Readarr":  UpdateReadarrIndexer,
    "Sonarr":   UpdateSonarrIndexer,
    "Whisparr": UpdateWhisparrIndexer,
  },
  "QualityProfiles": {
    "Lidarr": UpdateLidarrQualityProfile,
    "Radarr": UpdateRadarrQualityProfile,
    "Readarr": UpdateReadarrQualityProfile,
    "Sonarr": UpdateSonarrQualityProfile,
    "Whisparr": UpdateWhisparrQualityProfile,
  },
  "ImportLists": {
    "Lidarr": UpdateLidarrImportList,
    "Radarr": UpdateRadarrImportList,
    "Readarr": UpdateReadarrImportList,
    "Sonarr": UpdateSonarrImportList,
    "Whisparr": UpdateWhisparrImportList,
  },
  "Exclusions": {
    "Lidarr": UpdateLidarrExclusion,
    "Radarr": UpdateRadarrExclusion,
    "Readarr": UpdateReadarrExclusion,
    "Sonarr": UpdateSonarrExclusion,
    "Whisparr": UpdateWhisparrExclusion,
  },
}

export const test:  {[key: string]: {[key: string]: (...args: any[]) => Promise<string>;}} = {
  "DownloadClients": {
    "Lidarr":   TestLidarrDownloadClient,
    "Prowlarr": TestProwlarrDownloadClient,
    "Radarr":   TestRadarrDownloadClient,
    "Readarr":  TestReadarrDownloadClient,
    "Sonarr":   TestSonarrDownloadClient,
    "Whisparr": TestWhisparrDownloadClient,
  },
  "Indexers": {
    "Lidarr":   TestLidarrIndexer,
    "Prowlarr": TestProwlarrIndexer,
    "Radarr":   TestRadarrIndexer,
    "Readarr":  TestReadarrIndexer,
    "Sonarr":   TestSonarrIndexer,
    "Whisparr": TestWhisparrIndexer,
  },
  "ImportLists": {
    "Lidarr":   TestLidarrImportList,
    "Radarr":   TestRadarrImportList,
    "Readarr":  TestReadarrImportList,
    "Sonarr":   TestSonarrImportList,
    "Whisparr": TestWhisparrImportList,
  },
}

export const exportFile:  {[key: string]: (...args: any[]) => Promise<any>;} = {
  "DownloadClients": ExportDownloadClients,
  "Indexers":        ExportIndexer,
  "ImportLists":     ExportImportLists,
  "Exclusions":      ExportExclusions,
  "QualityProfiles": ExportQualityProfiles,
}

export const importFile:  {[key: string]: (...args: any[]) => Promise<any>;} = {
  "DownloadClients": ImportDownloadClients,
  "Indexers":        ImportIndexer,
  "ImportLists":     ImportImportLists,
  "Exclusions":      ImportExclusions,
  "QualityProfiles": ImportQualityProfiles,
}

export const add:  {[key: string]: {[key: string]: (...args: any[]) => Promise<string>;}} = {
  "DownloadClients": {
    "Lidarr":   AddLidarrDownloadClient,
    "Prowlarr": AddProwlarrDownloadClient,
    "Radarr":   AddRadarrDownloadClient,
    "Readarr":  AddReadarrDownloadClient,
    "Sonarr":   AddSonarrDownloadClient,
    "Whisparr": AddWhisparrDownloadClient,
  },
  "Indexers": {
    "Lidarr":   AddLidarrIndexer,
    "Prowlarr": AddProwlarrIndexer,
    "Radarr":   AddRadarrIndexer,
    "Readarr":  AddReadarrIndexer,
    "Sonarr":   AddSonarrIndexer,
    "Whisparr": AddWhisparrIndexer,
  },
  "ImportLists": {
    "Lidarr":   AddLidarrImportList,
    "Radarr":   AddRadarrImportList,
    "Readarr":  AddReadarrImportList,
    "Sonarr":   AddSonarrImportList,
    "Whisparr": AddWhisparrImportList,
  },
  "Exclusions": {
    "Lidarr":   AddLidarrExclusion,
    "Radarr":   AddRadarrExclusion,
    "Readarr":  AddReadarrExclusion,
    "Sonarr":   AddSonarrExclusion,
    "Whisparr": AddWhisparrExclusion,
  },
  "QualityProfiles": {
    "Lidarr": AddLidarrQualityProfile,
    "Radarr": AddRadarrQualityProfile,
    "Readarr": AddReadarrQualityProfile,
    "Sonarr": AddSonarrQualityProfile,
    "Whisparr": AddWhisparrQualityProfile,
  },
}