// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CheckUpdate():Promise<any>;

export function CreateShortcut():Promise<string>;

export function DownloadUpdate():Promise<any>;

export function GetConfig():Promise<any>;

export function LaunchInstaller(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function SaveConfigItem(arg1:string,arg2:any,arg3:boolean):Promise<any>;

export function Version():Promise<app.Version>;
