// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function CreateShortcut() {
  return window['go']['app']['App']['CreateShortcut']();
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetProgress() {
  return window['go']['app']['App']['GetProgress']();
}

export function IsWindows() {
  return window['go']['app']['App']['IsWindows']();
}

export function LaunchInstaller(arg1) {
  return window['go']['app']['App']['LaunchInstaller'](arg1);
}

export function Lock() {
  return window['go']['app']['App']['Lock']();
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['app']['App']['PickFolder'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function RLock() {
  return window['go']['app']['App']['RLock']();
}

export function RLocker() {
  return window['go']['app']['App']['RLocker']();
}

export function RUnlock() {
  return window['go']['app']['App']['RUnlock']();
}

export function SaveConfigItem(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveConfigItem'](arg1, arg2, arg3);
}

export function TryLock() {
  return window['go']['app']['App']['TryLock']();
}

export function TryRLock() {
  return window['go']['app']['App']['TryRLock']();
}

export function Unlock() {
  return window['go']['app']['App']['Unlock']();
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
