// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function CreateShortcut() {
  return window['go']['app']['App']['CreateShortcut']();
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function IsWindows() {
  return window['go']['app']['App']['IsWindows']();
}

export function LaunchInstaller() {
  return window['go']['app']['App']['LaunchInstaller']();
}

export function PickFolder(arg1) {
  return window['go']['app']['App']['PickFolder'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function SaveConfigItem(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveConfigItem'](arg1, arg2, arg3);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
