name: test-and-lint
on: push
permissions:
  contents: read
jobs:
  gotest:
    # description: "Runs `go test` against 3 operating systems."
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: go-generate
        run: go generate ./...
      - name: go-test
        run: |
          go test ./pkg/...

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@v1
        with:
          check_hidden: true
          skip: .git,node_modules,dist


  golangci-darwin:
    # description: "Runs golangci-lint on macos against freebsd and macos."
    strategy:
      matrix:
        os: [freebsd, darwin]
    name: golangci-lint
    runs-on: macos-latest
    env:
      GOOS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: go-generate
        run: GOOS=darwin go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
          args: --verbose ./ ./pkg/...

  golangci-linux:
    # description: "Runs golangci-lint on linux against linux and windows."
    strategy:
      matrix:
        os: [linux, windows]
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: go-generate
        run: GOOS=linux go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
          args: --verbose ./ ./pkg/...
