name: build-and-release
on:
  push:
    branches:
      - unstable
      - main
    tags:
      - v*
  pull_request:
    branches:
    - main
    - unstable
    - development
    - dn2_1st # temporary
jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Installs Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build Linux AMD64
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-0 libwebkit2gtk-4.0-dev
          wails build --platform linux/amd64 -webview2 embed -o toolbarr.amd64.linux
      - name: Build Linux ARM
        if: runner.os == 'Linux'
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: https://raspi.debian.net/tested/20230102_raspi_4_bullseye.img.xz
          bind_mount_repository: true
          image_additional_mb: 300
          commands: |
            apt update
            apt install -y libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu wget
            wget https://go.dev/dl/go1.20.2.linux-arm64.tar.gz
            tar -C /usr/local -xzf go1.20.2.linux-arm64.tar.gz
            PATH=$PATH:/usr/local/go/bin
            go install github.com/wailsapp/wails/v2/cmd/wails@latest
            wails build --platform linux/arm64 -webview2 embed -o toolbarr.arm64.linux
      - name: Build Windows
        if: runner.os == 'Windows'
        run: |
          wails build --platform windows/amd64 -webview2 embed -o Toolbarr.amd64.exe
          wails build --platform windows/arm64 -webview2 embed -o Toolbarr.arm64.exe
      - name: Build macOS
        if: runner.os == 'macOS'
        run: wails build --platform darwin/universal
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: toolbarr-${{ matrix.platform }}
          path: build/bin/*