name: build-and-release
on:
  push:
    branches:
      - unstable
      - main
    tags:
      - v*
  pull_request:
    branches:
    - main
    - unstable
    - development
    - dn2_1st # temporary
jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Installs Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Windows
        if: runner.os == 'Windows'
        run: |
          wails build -m -trimpath -platform windows/amd64 -webview2 embed -o Toolbarr.amd64.exe
          wails build -m -trimpath -platform windows/arm64 -webview2 embed -o Toolbarr.arm64.exe

      - name: Build macOS
        if: runner.os == 'macOS'
        run: wails build -m -trimpath --platform darwin/universal -webview2 embed

      - name: Build Linux AMD64
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-0 libwebkit2gtk-4.0-dev
          wails build -trimpath -platform linux/amd64 -webview2 embed -o toolbarr.amd64.linux

      # This one sucked to figure out, and it's slow. 
      - name: Build Linux ARM
        if: runner.os == 'Linux'
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: https://cdimage.ubuntu.com/releases/22.10/release/ubuntu-22.10-preinstalled-desktop-arm64+raspi.img.xz
          bind_mount_repository: true
          image_additional_mb: 900
          commands: |
            echo "update_initramfs=no" >> /etc/initramfs-tools/update-initramfs.conf
            apt update
            apt install -y libgtk-3-0 libwebkit2gtk-4.0-dev gcc wget
            wget https://go.dev/dl/go1.20.2.linux-arm64.tar.gz
            tar -C /usr/local -xzf go1.20.2.linux-arm64.tar.gz
            PATH=$PATH:/usr/local/go/bin
            go run github.com/wailsapp/wails/v2/cmd/wails@latest \
              build -s -m -trimpath -platform linux/arm64 -webview2 embed -o toolbarr.arm64.linux

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: toolbarr-${{ matrix.platform }}
          path: build/bin/*